version: '3'

services:

  postgres:
    image: postgres:15.2
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

  mongodb:
    image: mongo:5.0.17
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INIT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INIT_SECRET}
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_SECRET}

volumes:
  keycloak-data:
    external: false
  mongo-data:
    external: false

networks:
  local-keycloak:

