version: '3'

services:
  turkey-couch:
    build: couch
    container_name: turkey-couch
    restart: unless-stopped
    ports:
      - "5984:5984"
    volumes:
      - couch-data:/opt/couchdb/data

  postgres:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - local-keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

volumes:
  couch-data:
    external: false
  keycloak-data:
    external: false

networks:
  local-keycloak:

